### ISSUE TITLE
Radio-module not available

### ISSUE THREAD

**Issue by raffiniert** [marcovolpato00/SomfyControl#1]
Hey

thanks for your great work!
The link provided (https://www.ebay.com/itm/SOMFY-KEYGO-4-RTS-compatible-remote-control-replacement-433-42Mhz/182202217810?hash=item2a6c193552:g:1QYAAOSw5cNYEy14) does not work anymore... do you have an alternative?

Is it something like that? https://www.ebay.com/itm/SOMFY-KEYGO-4-RTS-remote-control-garage-command-433mhz-rolling-code-transmitter/333171950691?hash=item4d92988463:g:wzAAAOSwWlxcwt-W

Thanks
Raphael

**Comment by marcovolpato00** [comment]
Hi, sorry for responding so late but I noticed only now your issue.
The remote that you found should work, the only difference that you could encounter can be a slightly different PCB but that shouldn't be a big problem.
Thanks for pointing out that the link doesn't work anymore, I will update it 🙂

**Comment by raffiniert** [comment]
No worries, and thanks for the reply.
I only now saw that this remote (and your code, probably?) can only toggle the blinds? So a "close all" or "open all" is not possible?
I would have loved to connect a temperarture-sensor to it and control it depending on the measurement, but that sounds not possible like this...

**Comment by marcovolpato00** [comment]
Well, the main focus of this project is to have a web UI for remote controlling the blinds. 
I've never thought of anything automated but it is definitely possible to implement such a feature. I have done some changes that I don't have commited in this repo yet, so you can expect some updates in the near future and probably will implement some kind of temperature/light change based automation. 
Thanks for your suggestions.
